version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run start-watch
    volumes: 
      - ./api:/usr/app/
      - ./api/node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://${MONGODB_APPLICATION_USER}:${MONGODB_APPLICATION_PASS}@mongo:27017/${MONGODB_APPLICATION_DATABASE}
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGODB_ADMIN_USER: ${MONGODB_ADMIN_USER}
      MONGODB_ADMIN_PASS: ${MONGODB_ADMIN_PASS}
      MONGODB_APPLICATION_DATABASE: ${MONGODB_APPLICATION_DATABASE}
      MONGODB_APPLICATION_USER: ${MONGODB_APPLICATION_USER}
      MONGODB_APPLICATION_PASS: ${MONGODB_APPLICATION_PASS}